[package]
name = "piim-qdrant"
version = "0.3.1"
edition = "2024"


[dependencies]
piim-common = { path = "../common" }
anyhow = "1.0"
async-trait = "0.1"
kameo = "0.22"
qdrant-client = "1.19"
rust-mcp-sdk = { version = "2.0", features = ["stdio", "server"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["full"] }
tokio-stream = "0.1"
uuid = { version = "1.27", features = ["v4"] }
