[package]
name = "piim-common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
hex = "0.4"
kameo = "0.22"
rust-mcp-sdk = { version = "2.0", features = ["stdio", "server"] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
fastembed = { version = "7", features = ["qwen3"]}
candle-core = { version = "0.11"}
